# Generated by Django 5.1 on 2024-08-22 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcomment',
            old_name='content',
            new_name='comment',
        ),
    ]
