# Generated by Django 5.1 on 2024-08-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_like_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='p_hit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
