# Generated by Django 5.1 on 2024-08-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='hashtag',
            field=models.ManyToManyField(related_name='product', to='products.hashtag'),
        ),
    ]
